export const CUR_SEASON = "2024-25";

export const StatKeyToShortLabel = {
  PTS: "PTS",
  REB: "REB",
  AST: "AST",
  STL: "STL",
  BLK: "BLK",
  TO: "TO",
  FGM: "FGM",
  FGA: "FGA",
  FG_PCT: "FG%",
  FG3M: "3PM",
  FG3A: "3PA",
  FG3_PCT: "3P%",
  FTM: "FTM",
  FTA: "FTA",
  FT_PCT: "FT%",
  PF: "PF",
  DREB: "DREB",
  OREB: "OREB",
  MIN: "MIN",
  PLUS_MINUS: "+/-",
} as const;

export const TeamTricodeToColor: Record<string, string> = {
  ATL: "#E03A3E",
  BOS: "#007A33",
  BKN: "#000000",
  CHA: "#00788C",
  CHI: "#CE1141",
  CLE: "#6F263D",
  DAL: "#00538C",
  DEN: "#0E2240",
  DET: "#C8102E",
  GSW: "#1D428A",
  HOU: "#CE1141",
  IND: "#002D62",
  LAC: "#C8102E",
  LAL: "#552583",
  MEM: "#5D76A9",
  MIA: "#98002E",
  MIL: "#00471B",
  MIN: "#0C2340",
  NOP: "#0C2340",
  NYK: "#006BB6",
  OKC: "#007AC1",
  ORL: "#0077C0",
  PHI: "#006BB6",
  PHX: "#1D1160",
  POR: "#E03A3E",
  SAC: "#5A2D81",
  SAS: "#C4CED4",
  TOR: "#CE1141",
  UTA: "#002B5C",
  WAS: "#002B5C",
};

export const EventTypes = {
  FIELD_GOAL_MADE: 1,
  FIELD_GOAL_MISSED: 2,
  FREE_THROW: 3,
  REBOUND: 4,
  TURNOVER: 5,
  FOUL: 6,
  VIOLATION: 7,
  SUBSTITUTION: 8,
  TIMEOUT: 9,
  JUMP_BALL: 10,
  EJECTION: 11,
  PERIOD_BEGIN: 12,
  PERIOD_END: 13,
  INSTANT_REPLAY: 18,
};

export const ShotActionTypes = {
  1: "JUMP_SHOT",
  2: "RUNNING_JUMP_SHOT",
  3: "HOOK_SHOT",
  5: "LAYUP",
  6: "DRIVING_LAYUP",
  7: "DUNK",
  9: "DRIVING_DUNK",
  41: "RUNNING_LAYUP",
  43: "ALLEY_OOP_LAYUP",
  44: "REVERSE_LAYUP",
  47: "TURNAROUND_JUMP_SHOT",
  50: "RUNNING_DUNK",
  51: "REVERSE_DUNK",
  52: "ALLEY_OOP_DUNK",
  57: "DRIVING_HOOK_SHOT",
  58: "TURNAROUND_HOOK_SHOT",
  63: "FADEAWAY_JUMPER",
  66: "JUMP_BANK_SHOT",
  67: "HOOK_BANK_SHOT",
  71: "FINGER_ROLL_LAYUP",
  72: "PUTBACK_LAYUP",
  73: "DRIVING_REVERSE_LAYUP",
  74: "RUNNING_REVERSE_LAYUP",
  75: "DRIVING_FINGER_ROLL_LAYUP",
  76: "RUNNING_FINGER_ROLL_LAYUP",
  78: "FLOATING_JUMP_SHOT",
  79: "PULLUP_JUMP_SHOT",
  80: "STEPBACK_JUMP_SHOT",
  83: "FADEAWAY_BANK_SHOT",
  85: "TURNAROUND_BANK_SHOT",
  86: "TURNAROUND_FADEAWAY_SHOT",
  87: "PUTBACK_DUNK",
  93: "DRIVING_BANK_HOOK_SHOT",
  96: "TURNAROUND_BANK_HOOK_SHOT",
  97: "TIP_LAYUP_SHOT",
  98: "CUTTING_LAYUP_SHOT",
  99: "CUTTING_FINGER_ROLL_LAYUP_SHOT",
  100: "RUNNING_ALLEY_OOP_LAYUP_SHOT",
  101: "DRIVING_FLOATING_JUMP_SHOT",
  102: "DRIVING_FLOATING_BANK_JUMP_SHOT",
  103: "RUNNING_PULLUP_JUMP_SHOT",
  104: "STEPBACK_BANK_JUMP_SHOT",
  105: "TURNAROUND_FADEAWAY_BANK_JUMP_SHOT",
  106: "RUNNING_ALLEY_OOP_DUNK_SHOT",
  107: "TIP_DUNK_SHOT",
  108: "CUTTING_DUNK_SHOT",
  109: "REVERSE_DUNK_SHOT",
  110: "RUNNING_REVERSE_DUNK_SHOT",
};

export const ActionTypesByEventType = {
  1: ShotActionTypes,
  2: ShotActionTypes,
  3: {
    10: "FIRST_OF_ONE",
    11: "FIRST_OF_TWO",
    12: "SECOND_OF_TWO",
    13: "FIRST_OF_THREE",
    14: "SECOND_OF_THREE",
    15: "THIRD_OF_THREE",
    16: "TECHNICAL",
    18: "FIRST_OF_FLAGRANT_OF_TWO",
    19: "SECOND_OF_FLAGRANT_OF_TWO",
    20: "FIRST_OF_FLAGRANT_OF_ONE",
    21: "FIRST_OF_TECHNICAL",
    22: "SECOND_OF_TECHNICAL",
    25: "FIRST_OF_CLEAR_PATH",
    26: "SECOND_OF_CLEAR_PATH",
    27: "FIRST_OF_FLAGRANT_OF_THREE",
    28: "SECOND_OF_FLAGRANT_OF_THREE",
    29: "THIRD_OF_FLAGRANT_OF_THREE",
  },
  4: {
    0: "DEFENSIVE_REBOUND",
    1: "OFFENSIVE_REBOUND",
  },
  5: {
    0: "TURNOVER", // Unclear
    1: "STEAL",
    2: "STEAL",
    4: "TRAVELING",
    6: "DOUBLE_DRIBBLE",
    7: "DISCONTINUE_DRIBBLE",
    8: "3_SECOND_VIOLATION",
    9: "5_SECOND_VIOLATION",
    10: "8_SECOND_VIOLATION",
    11: "SHOT_CLOCK_VIOLATION",
    12: "INBOUND",
    13: "BACKCOURT",
    15: "OFFENSIVE_GOALTENDING",
    17: "LANE_VIOLATION",
    18: "JUMP_BALL_VIOLATION",
    19: "KICK_BALL",
    20: "ILLEGAL_ASSIST",
    21: "PALMING",
    35: "BASKET_FROM_BELOW",
    37: "OFFENSIVE_FOUL",
    39: "STEP_OUT_OF_BOUNDS",
    40: "OUT_OF_BOUNDS",
    42: "EXCESSIVE_TIMEOUT",
    44: "TOO_MANY_PLAYERS",
    45: "BAD_PASS",
  },
  6: {
    0: "TEAM", // TODO Confirm
    1: "PERSONAL",
    2: "SHOOTING",
    3: "LOOSE_BALL",
    4: "OFFENSIVE",
    6: "AWAY_FROM_PLAY",
    9: "CLEAR_PATH",
    10: "DOUBLE_PERSONAL",
    11: "TECHNICAL", // TODO Confirm
    12: "NON_UNSPORTSMANLIKE",
    13: "HANGING_TECHNICAL",
    14: "FLAGRANT_TYPE_1",
    15: "FLAGRANT_TYPE_2",
    16: "DOUBLE_TECHNICAL",
    17: "DEFENSIVE_3_SECONDS",
    18: "DELAY",
    25: "EXCESSIVE_TIMEOUT",
    26: "OFFENSIVE_CHARGE",
    28: "PERSONAL_TAKE",
    30: "TOO_MANY_PLAYERS",
    31: "TRANSITION_TAKE",
    32: "FLOPPING_TECHNICAL",
  },
  7: {
    1: "DELAY_OF_GAME",
    2: "DEFENSIVE_GOALTENDING",
    3: "LANE",
    4: "JUMP_BALL",
    5: "KICK_BALL",
  },
  8: {
    0: "SUBSTITUTION",
  },
  9: {
    1: "REGULAR",
    7: "COACH_CHALLENGE",
  },
  10: {
    0: "JUMP_BALL",
    1: "COACH_CHALLENGE",
  },
  11: {
    4: "OTHER",
  },
  12: {
    0: "QUARTER_OVERTIME_START",
  },
  13: {
    0: "QUARTER_OVERTIME_END",
  },
  18: {
    0: "INSTANT_REPLAY",
    1: "INSTANT_REPLAY",
    2: "INSTANT_REPLAY",
    3: "INSTANT_REPLAY",
    4: "INSTANT_REPLAY",
    5: "INSTANT_REPLAY",
    6: "INSTANT_REPLAY",
    7: "INSTANT_REPLAY",
  },
};

export const ShotActionTypeToLabel: Record<
  keyof typeof ShotActionTypes,
  string
> = {
  1: "Jump Shot",
  2: "Running Jump Shot",
  3: "Hook Shot",
  5: "Layup",
  6: "Driving Layup",
  7: "Dunk",
  9: "Driving Dunk",
  41: "Running Layup",
  43: "Alley Oop Layup",
  44: "Reverse Layup",
  47: "Turnaround Jump Shot",
  50: "Running Dunk",
  51: "Reverse Dunk",
  52: "Alley Oop Dunk",
  57: "Driving Hook Shot",
  58: "Turnaround Hook Shot",
  63: "Fadeaway Jumper",
  66: "Jump Bank Shot",
  67: "Hook Bank Shot",
  71: "Finger Roll Layup",
  72: "Putback Layup",
  73: "Driving Reverse Layup",
  74: "Running Reverse Layup",
  75: "Driving Finger Roll Layup",
  76: "Running Finger Roll Layup",
  78: "Floating Jump Shot",
  79: "Pullup Jump Shot",
  80: "Stepback Jump Shot",
  83: "Fadeaway Bank Shot",
  85: "Turnaround Bank Shot",
  86: "Turnaround Fadeaway Shot",
  87: "Putback Dunk",
  93: "Driving Bank Hook Shot",
  96: "Turnaround Bank Hook Shot",
  97: "Tip Layup Shot",
  98: "Cutting Layup Shot",
  99: "Cutting Finger Roll Layup Shot",
  100: "Running Alley Oop Layup Shot",
  101: "Driving Floating Jump Shot",
  102: "Driving Floating Bank Jump Shot",
  103: "Running Pullup Jump Shot",
  104: "Stepback Bank Jump Shot",
  105: "Turnaround Fadeaway Bank Jump Shot",
  106: "Running Alley Oop Dunk Shot",
  107: "Tip Dunk Shot",
  108: "Cutting Dunk Shot",
  109: "Reverse Dunk Shot",
  110: "Running Reverse Dunk Shot",
};
