type PlayVideo = {
  url: string;
  thumb: string;
  duration: number;
  subtitle: string;
};

type PlayByPlay = {
  GAME_ID: string;
  EVENTNUM: number;
  EVENTMSGTYPE: number;
  EVENTMSGACTIONTYPE: number;
  PERIOD: number;
  WCTIMESTRING: string;
  PCTIMESTRING: string;
  HOMEDESCRIPTION: string | null;
  NEUTRALDESCRIPTION: string | null;
  VISITORDESCRIPTION: string | null;
  SCORE: string | null;
  SCOREMARGIN: string | null;
  PERSON1TYPE: number;
  PLAYER1_ID: number;
  PLAYER1_NAME: string | null;
  PLAYER1_TEAM_ID: number | null;
  PLAYER1_TEAM_CITY: string | null;
  PLAYER1_TEAM_NICKNAME: string | null;
  PLAYER1_TEAM_ABBREVIATION: string | null;
  PERSON2TYPE: number;
  PLAYER2_ID: number;
  PLAYER2_NAME: string | null;
  PLAYER2_TEAM_ID: number | null;
  PLAYER2_TEAM_CITY: string | null;
  PLAYER2_TEAM_NICKNAME: string | null;
  PLAYER2_TEAM_ABBREVIATION: string | null;
  PERSON3TYPE: number;
  PLAYER3_ID: number;
  PLAYER3_NAME: string | null;
  PLAYER3_TEAM_ID: number | null;
  PLAYER3_TEAM_CITY: string | null;
  PLAYER3_TEAM_NICKNAME: string | null;
  PLAYER3_TEAM_ABBREVIATION: string | null;
  VIDEO_AVAILABLE_FLAG: boolean;
  video: PlayVideo | null;
};

type GameTeamStats = {
  GAME_ID: string;
  TEAM_ID: number;
  TEAM_NAME: string;
  TEAM_ABBREVIATION: string;
  TEAM_CITY: string;
  MIN: string;
  FGM: number;
  FGA: number;
  FG_PCT: number;
  FG3M: number;
  FG3A: number;
  FG3_PCT: number;
  FTM: number;
  FTA: number;
  FT_PCT: number;
  OREB: number;
  DREB: number;
  REB: number;
  AST: number;
  STL: number;
  BLK: number;
  TO: number;
  PF: number;
  PTS: number;
  PLUS_MINUS: number;
};

type GamePlayerStats = {
  GAME_ID: string;
  TEAM_ID: number;
  TEAM_ABREVIATION: string;
  TEAM_CITY: string;
  PLAYER_ID: number;
  PLAYER_NAME: string;
  NICKNAME: string;
  START_POSITION: string;
  COMMENT: string;
  MIN: string | null;
  FGM: number | null;
  FGA: number | null;
  FG_PCT: number | null;
  FG3M: number | null;
  FG3A: number | null;
  FG3_PCT: number | null;
  FTM: number | null;
  FTA: number | null;
  FT_PCT: number | null;
  OREB: number | null;
  DREB: number | null;
  REB: number | null;
  AST: number | null;
  STL: number | null;
  BLK: number | null;
  TO: number | null;
  PF: number | null;
  PTS: number | null;
  PLUS_MINUS: number | null;
};

type GameStarterBenchStats<T extends "Starters" | "Bench"> = {
  GAME_ID: string;
  TEAM_ID: number;
  TEAM_NAME: string;
  TEAM_ABBREVIATION: string;
  TEAM_CITY: string;
  STARTERS_BENCH: T;
  MIN: string;
  FGM: number;
  FGA: number;
  FG_PCT: number;
  FG3M: number;
  FG3A: number;
  FG3_PCT: number;
  FTM: number;
  FTA: number;
  FT_PCT: number;
  OREB: number;
  DREB: number;
  REB: number;
  AST: number;
  STL: number;
  BLK: number;
  TO: number;
  PF: number;
  PTS: number;
};

type GameRotation = {
  GAME_ID: string;
  TEAM_ID: number;
  TEAM_CITY: string;
  TEAM_NAME: string;
  PERSON_ID: number;
  PLAYER_FIRST: string;
  PLAYER_LAST: string;
  IN_TIME_REAL: number;
  OUT_TIME_REAL: number;
  PLAYER_PTS: number;
  PT_DIFF: number;
  USG_PCT: number;
};

export type GameData = {
  GAME_ID: string;
  GAME_DATE: string;
  playbyplay: PlayByPlay[];
  homeTeam: {
    stats: GameTeamStats;
    playerStats: GamePlayerStats[];
    startersStats: GameStarterBenchStats<"Starters">;
    benchStats: GameStarterBenchStats<"Bench">;
    rotations: GameRotation[];
  };
  awayTeam: {
    stats: GameTeamStats;
    playerStats: GamePlayerStats[];
    startersStats: GameStarterBenchStats<"Starters">;
    benchStats: GameStarterBenchStats<"Bench">;
    rotations: GameRotation[];
  };
};

export type TeamSeasonAverages = {
  GROUP_SET: string;
  GROUP_VALUE: string;
  SEASON_YEAR: string;
  GP: number;
  W: number;
  L: number;
  W_PCT: number;
  MIN: number;
  FGM: number;
  FGA: number;
  FG_PCT: number;
  FG3M: number;
  FG3A: number;
  FG3_PCT: number;
  FTM: number;
  FTA: number;
  FT_PCT: number;
  OREB: number;
  DREB: number;
  REB: number;
  AST: number;
  TOV: number;
  STL: number;
  BLK: number;
  BLKA: number;
  PF: number;
  PFD: number;
  PTS: number;
  PLUS_MINUS: number;
  GP_RANK: number;
  W_RANK: number;
  L_RANK: number;
  W_PCT_RANK: number;
  MIN_RANK: number;
  FGM_RANK: number;
  FGA_RANK: number;
  FG_PCT_RANK: number;
  FG3M_RANK: number;
  FG3A_RANK: number;
  FG3_PCT_RANK: number;
  FTM_RANK: number;
  FTA_RANK: number;
  FT_PCT_RANK: number;
  OREB_RANK: number;
  DREB_RANK: number;
  REB_RANK: number;
  AST_RANK: number;
  TOV_RANK: number;
  STL_RANK: number;
  BLK_RANK: number;
  BLKA_RANK: number;
  PF_RANK: number;
  PFD_RANK: number;
  PTS_RANK: number;
  PLUS_MINUS_RANK: number;
  TEAM_ID: string;
};
